[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  exclude = [
    # By Glob pattern
    '*admin',
    'https://kingwoodbuilders.com/sample-page',
    'https://kingwoodbuilders.com/home',
    'https://kingwoodbuilders.com/landing'
  ]